version: "3"
services:
  web:
    build: ../airdrome_hud/
    ports:
      - "${WEB_PORT}:3000"
    restart: unless-stopped
  api:
    build: ../airdrome_api/
    ports:
      - "${APP_PORT}:8080"
    environment:
      DOMAIN: $DOMAIN
      DATABASE_URL: $DATABASE_URL
      APP_ROOT: $APP_ROOT
      OBEX_PATH: $OBEX_PATH
      OBJECTS_PATH: $OBJECTS_PATH
      B2_APPLICATION_KEY: $B2_APPLICATION_KEY
      B2_APPLICATION_KEY_ID: $B2_APPLICATION_KEY_ID
      B2_APPLICATION_TOKEN: $B2_APPLICATION_TOKEN
      B2_BUCKET_ID: $B2_BUCKET_ID
      B2_BUCKET_NAME: $B2_BUCKET_NAME
    restart: unless-stopped
    depends_on: migrations_job
    command: bash -c "sleep 60 && ./airdrome_api"
  migrations_job:
    build: ../jobs/migrations_job/
    environment:
      DATABASE_URL: $DATABASE_URL
    depends_on: db
    command: bash -c "sleep 30 && sh run.sh"
#  certbot_job:
#    image: certbot/certbot
#    volumes:
#      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
#      - ./letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
  proxy:
    build: ./proxy/
    ports:
      - "${PROXY_PORT}:80"
      - "${PROXY_PORT_ENCRYPTED}:443"
    environment:
      PROXY_CONF: $PROXY_CONF
    restart: always
    volumes:
      - ./proxy/${ENVIRONMENT}_proxy.conf:/etc/nginx/conf.d/proxy.conf
#      - /etc/letsencrypt/live/airdrome.org/fullchain.pem:/etc/letsencrypt/live/airdrome.org/fullchain.pem
#      - /etc/letsencrypt/live/airdrome.org/privkey.pem:/etc/letsencrypt/live/airdrome.org/privkey.pem
  db:
    image: mysql
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - .:/docker-entrypoint-initdb.d/:z
    networks:
      - airdrome-network
