name: API                                                                                           
                                                                                                     
on:                                                                                                 
  pull_request:                                                                                     
    paths:                                                                                          
      - 'airdrome_api/*'                                                                                          
  push:                                                                                     
    branches: master
    paths:                                                                                          
      - 'airdrome_api/*'                                                                                          

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo build
        run: cargo build --verbose
        working-directory: ./airdrome_api
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    env:
      B2_APPLICATION_KEY_NAME: api-test-key
      B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
      B2_APPLICATION_TOKEN: ${{ secrets.B2_APPLICATION_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cargo build
        run: cargo build
        working-directory: ./airdrome_api
      - name: Cargo test
        run: cargo test --verbose
        working-directory: ./airdrome_api

