name: API                                                                                           
                                                                                                     
on:                                                                                                 
  pull_request:                                                                                     
    paths:                                                                                          
      - 'airdrome_api/*'                                                                                          
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Cargo tests
        run: cargo test --verbose
        working-directory: ./airdrome_api

