name: API

on:
  pull_request:
    paths:
      - 'airdrome_api/*'
  push:
    branches: master
    paths:
      - 'airdrome_api/*'
defaults:
  run:
    working-directory: ./airdrome_api
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cargo check
        run: cargo check -v
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    env:
      B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
      B2_APPLICATION_TOKEN: ${{ secrets.B2_APPLICATION_TOKEN }}
      B2_TEST_BUCKET_NAME: "api-test"
      B2_TEST_BUCKET_ID: ${{ secrets.B2_TEST_BUCKET_ID }}
      B2_TEST_FILE_ID: ${{ secrets.B2_TEST_FILE_ID }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose

