name: HUD                                                                                           
                                                                                                     
on:                                                                                                 
  pull_request:                                                                                     
    paths:                                                                                          
      - 'airdrome_hud/*'                                                                                          
  push:                                                                                     
    branches: master
    paths:                                                                                          
      - 'airdrome_hud/*'                                                                                          
defaults:
  run:
    working-directory: ./airdrome_hud
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cargo check
        run: cargo check -v
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    env:
      B2_APPLICATION_KEY_NAME: api-test-key
      B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
      B2_APPLICATION_TOKEN: ${{ secrets.B2_APPLICATION_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose

